/**
 * nftables ruleset per gateway.
 *
 * One dedicated `table inet opnmesh`, replaced atomically on every reload;
 * the operator's own tables are never touched. The forward chain drops by
 * default and accepts exactly the traffic the topology says should flow:
 *
 *  - this site's shared LANs ⇄ every site reachable from here;
 *  - relayed site pairs (only on a hub);
 *  - roaming clients into this site, and (on their relay) onward to
 *    outbound-only sites — per client when the client is restricted;
 *  - nothing may open a connection to a client unless the client allows it.
 *
 * Named counters per ordered site pair (and per site ⇄ clients) sit before
 * the verdicts, so the controller can read a site-to-site traffic matrix
 * straight from the forwarding gateway. No NAT exists except the explicit
 * masquerade layout, and only on that gateway.
 */
import type { ClientSnapshot, Snapshot } from "../model";
import {
  activeClients,
  clientAllows,
  clientRouteFrom,
  clientTransitViaHub,
  meshSite,
  reachableSitesFrom,
  relayedPairs,
  sharedCidrs,
  type MeshSite,
} from "../topology";

export function nftIdent(slug: string): string {
  return slug.replace(/[^a-z0-9]/g, "_");
}

export function lanSetName(site: { slug: string }): string {
  return `lan_${nftIdent(site.slug)}`;
}

export function pairCounterName(from: { slug: string }, to: { slug: string }): string {
  return `c_${nftIdent(from.slug)}_to_${nftIdent(to.slug)}`;
}

export function clientCounterNames(site: { slug: string }): { toSite: string; fromSite: string } {
  return { toSite: `c_clients_to_${nftIdent(site.slug)}`, fromSite: `c_${nftIdent(site.slug)}_to_clients` };
}

function setBlock(name: string, elements: string[]): string[] {
  return [
    `  set ${name} {`,
    "    type ipv4_addr",
    "    flags interval",
    `    elements = { ${elements.join(", ")} }`,
    "  }",
  ];
}

/** Ordered site pairs this gateway forwards between (own and relayed). */
export function counterPairs(snap: Snapshot, g: MeshSite): Array<[MeshSite, MeshSite]> {
  const pairs: Array<[MeshSite, MeshSite]> = [];
  for (const p of reachableSitesFrom(snap, g.id)) pairs.push([g, p], [p, g]);
  for (const [a, b] of relayedPairs(snap, g.id)) pairs.push([a, b], [b, a]);
  return pairs;
}

export function generateNftables(snap: Snapshot, siteId: string): string {
  const g = meshSite(snap, siteId);
  const wg = snap.settings.interfaceName;
  const remote = reachableSitesFrom(snap, g.id);
  const relayed = relayedPairs(snap, g.id);
  const clients = activeClients(snap);
  // Clients whose traffic can arrive here: direct peers of this gateway, and
  // clients an outbound-only site receives through its relay hub.
  const reachesHere = (c: ClientSnapshot) => clientRouteFrom(snap, g.id, c) !== null;

  // Split into the unrestricted (one set) and the restricted (a rule each).
  const open = clients.filter((c) => reachesHere(c) && c.allowedSiteIds === null);
  const restricted = clients.filter((c) => reachesHere(c) && c.allowedSiteIds !== null);
  const inboundOk = clients.filter((c) => reachesHere(c) && c.allowInbound);

  const lines: string[] = [
    "#!/usr/sbin/nft -f",
    "# Generated by OPNmesh v2 — do not edit; overwritten on reconcile.",
    `# gateway: ${g.slug}`,
    "",
    "table inet opnmesh {}",
    "delete table inet opnmesh",
    "",
    "table inet opnmesh {",
  ];

  // Sets: this site and every site whose traffic passes through here.
  const setSites = new Map<string, MeshSite>([[g.id, g]]);
  for (const p of remote) setSites.set(p.id, p);
  for (const [a, b] of relayed) {
    setSites.set(a.id, a);
    setSites.set(b.id, b);
  }
  for (const s of [...setSites.values()].sort((a, b) => a.slug.localeCompare(b.slug))) {
    const cidrs = sharedCidrs(s);
    if (cidrs.length === 0) continue;
    lines.push(...setBlock(lanSetName(s), cidrs));
  }
  lines.push(...setBlock("clients", [snap.settings.clientCidr]));
  if (open.length > 0) lines.push(...setBlock("clients_open", open.map((c) => `${c.tunnelIp}/32`)));

  // Counters.
  lines.push("");
  const pairs = counterPairs(snap, g);
  for (const [from, to] of pairs) lines.push(`  counter ${pairCounterName(from, to)} {}`);
  const cc = clientCounterNames(g);
  lines.push(`  counter ${cc.toSite} {}`, `  counter ${cc.fromSite} {}`);

  const self = sharedCidrs(g).length > 0 ? lanSetName(g) : null;
  const has = (s: MeshSite) => sharedCidrs(s).length > 0;

  lines.push("", "  chain forward {", "    type filter hook forward priority filter; policy drop;");

  // Count first, decide later: counting rules carry no verdict, and they sit
  // ahead of the established/related accept so every packet of every
  // connection is counted, not just the first.
  lines.push("", "    # Traffic matrix counters (no verdict).");
  for (const [from, to] of pairs) {
    if (!has(from) || !has(to)) continue;
    lines.push(
      `    ip saddr @${lanSetName(from)} ip daddr @${lanSetName(to)} counter name "${pairCounterName(from, to)}"`,
    );
  }
  if (self) {
    lines.push(
      `    ip saddr @clients ip daddr @${self} counter name "${cc.toSite}"`,
      `    ip saddr @${self} ip daddr @clients counter name "${cc.fromSite}"`,
    );
  }

  lines.push(
    "",
    "    ct state established,related accept",
    "    ct state invalid drop",
    "",
    "    # Clamp TCP MSS to the tunnel path MTU in both directions.",
    `    oifname "${wg}" tcp flags syn tcp option maxseg size set rt mtu`,
    `    iifname "${wg}" tcp flags syn tcp option maxseg size set rt mtu`,
  );

  lines.push("", "    # Nothing opens connections to roaming clients, unless a client allows it.");
  for (const c of inboundOk) lines.push(`    oifname "${wg}" ip daddr ${c.tunnelIp} accept`);
  lines.push(`    oifname "${wg}" ip daddr @clients ct state new drop`);

  if (self && remote.some(has)) {
    lines.push("", "    # This site's LANs to and from every reachable site.");
    for (const p of remote) {
      if (!has(p)) continue;
      lines.push(
        `    iifname != "${wg}" oifname "${wg}" ip saddr @${self} ip daddr @${lanSetName(p)} accept`,
        `    iifname "${wg}" oifname != "${wg}" ip saddr @${lanSetName(p)} ip daddr @${self} accept`,
      );
    }
  }

  if (relayed.length > 0) {
    lines.push("", "    # Relayed site pairs (this gateway is their hub).");
    for (const [a, b] of relayed) {
      if (!has(a) || !has(b)) continue;
      lines.push(
        `    iifname "${wg}" oifname "${wg}" ip saddr @${lanSetName(a)} ip daddr @${lanSetName(b)} accept`,
        `    iifname "${wg}" oifname "${wg}" ip saddr @${lanSetName(b)} ip daddr @${lanSetName(a)} accept`,
      );
    }
  }

  if (self && open.length > 0) {
    lines.push("", "    # Roaming clients into this site.");
    lines.push(`    iifname "${wg}" oifname != "${wg}" ip saddr @clients_open ip daddr @${self} accept`);
  }
  if (self) {
    for (const c of restricted) {
      if (clientAllows(c, g.id)) {
        lines.push(`    iifname "${wg}" oifname != "${wg}" ip saddr ${c.tunnelIp} ip daddr @${self} accept`);
      }
    }
  }

  // Clients relayed onward to outbound-only sites through this hub.
  const relayLines: string[] = [];
  for (const c of [...open, ...restricted]) {
    for (const o of clientTransitViaHub(snap, g.id, c)) {
      if (!has(o)) continue;
      const src = c.allowedSiteIds === null ? "@clients_open" : c.tunnelIp;
      const line = `    iifname "${wg}" oifname "${wg}" ip saddr ${src} ip daddr @${lanSetName(o)} accept`;
      if (!relayLines.includes(line)) relayLines.push(line);
    }
  }
  if (relayLines.length > 0) {
    lines.push("", "    # Roaming clients relayed to outbound-only sites through this hub.", ...relayLines);
  }

  lines.push("  }");

  if (g.routerLayout === "masquerade") {
    lines.push(
      "",
      "  # Masquerade layout: traffic entering this site from the mesh is",
      "  # source-translated to this gateway so the router needs no static routes.",
      "  chain postrouting {",
      "    type nat hook postrouting priority srcnat; policy accept;",
      `    iifname "${wg}" oifname != "${wg}" masquerade`,
      "  }",
    );
  }

  lines.push("}");
  return lines.join("\n") + "\n";
}
