/** sysctl fragment for gateways: forwarding on, nothing else touched. */
import type { Snapshot } from "../model";
import { meshSite } from "../topology";

export function generateSysctl(snap: Snapshot, siteId: string): string {
  const g = meshSite(snap, siteId);
  return [
    "# Generated by OPNmesh v2 — do not edit; overwritten on reconcile.",
    `# gateway: ${g.slug}`,
    "net.ipv4.ip_forward = 1",
    "",
  ].join("\n");
}
