/**
 * WireGuard configuration for gateways and clients.
 *
 * Invariants (re-checked independently in validate.ts):
 *  - AllowedIPs per peer is exactly: that peer's tunnel /32, its shared LANs,
 *    the sites it relays for from here, and the client /32s it carries.
 *    Never 0.0.0.0/0, never anything unexplained.
 *  - Gateway private keys never appear; the interface loads it from a
 *    root-only path via the single sanctioned PostUp.
 *  - Client configs carry a placeholder the server fills at render time, so
 *    the generator stays pure and the bundle hash stays stable.
 *  - Output is deterministic: peers sorted by tunnel IP, no timestamps.
 */
import type { ClientSnapshot, Snapshot } from "../model";
import { compareIp, parseCidr } from "../ip";
import {
  activeClients,
  arePeered,
  clientCarriedByEntry,
  clientEntrySites,
  clientRelaySite,
  clientRouteFrom,
  endpointOf,
  isReachable,
  listenPortOf,
  meshSite,
  meshSites,
  mtuOf,
  sharedCidrs,
  transitDestinationsVia,
  type MeshSite,
} from "../topology";

export const CLIENT_PRIVATE_KEY_PLACEHOLDER = "{{PRIVATE_KEY}}";
export const HEADER = "# Generated by OPNmesh v2 — do not edit; overwritten on reconcile.";

/** AllowedIPs gateway `g` lists for peer gateway `p`. */
export function gatewayPeerAllowedIps(snap: Snapshot, g: MeshSite, p: MeshSite): string[] {
  const ips: string[] = [`${p.gateway.tunnelIp}/32`, ...sharedCidrs(p)];
  const transits = transitDestinationsVia(snap, g.id, p.id).sort((a, b) =>
    compareIp(a.gateway.tunnelIp, b.gateway.tunnelIp),
  );
  for (const t of transits) ips.push(`${t.gateway.tunnelIp}/32`, ...sharedCidrs(t));
  for (const c of activeClients(snap)) {
    if (clientRouteFrom(snap, g.id, c) === p.id) ips.push(`${c.tunnelIp}/32`);
  }
  return ips;
}

export function generateGatewayConf(snap: Snapshot, siteId: string): string {
  const g = meshSite(snap, siteId);
  const prefix = parseCidr(snap.settings.gatewayCidr)?.prefix ?? 24;
  const lines: string[] = [
    HEADER,
    `# gateway: ${g.slug}`,
    "",
    "[Interface]",
    `Address = ${g.gateway.tunnelIp}/${prefix}`,
    `ListenPort = ${listenPortOf(snap, g)}`,
    `MTU = ${mtuOf(snap, g)}`,
    `PostUp = wg set %i private-key ${snap.settings.privateKeyPath}`,
  ];

  const peers = meshSites(snap)
    .filter((p) => p.id !== g.id && arePeered(snap, g.id, p.id))
    .sort((a, b) => compareIp(a.gateway.tunnelIp, b.gateway.tunnelIp));

  for (const p of peers) {
    lines.push("", "[Peer]", `# site: ${p.slug}`, `PublicKey = ${p.gateway.publicKey}`);
    const ep = endpointOf(snap, p);
    if (ep !== null) lines.push(`Endpoint = ${ep}`);
    lines.push(`AllowedIPs = ${gatewayPeerAllowedIps(snap, g, p).join(", ")}`);
    // An outbound-only gateway must dial out and keep its NAT mapping alive.
    if (!isReachable(g)) lines.push(`PersistentKeepalive = ${snap.settings.keepalive}`);
  }

  for (const c of activeClients(snap)) {
    if (!clientEntrySites(snap, c).some((e) => e.id === g.id)) continue;
    lines.push(
      "",
      "[Peer]",
      `# client: ${c.slug}`,
      `PublicKey = ${c.publicKey}`,
      // Roaming: no Endpoint, learned from the handshake. Exactly its /32.
      `AllowedIPs = ${c.tunnelIp}/32`,
    );
  }

  return lines.join("\n") + "\n";
}

/** The DNS line for a client, if any allowed site declares a resolver. */
export function clientDns(snap: Snapshot, c: ClientSnapshot): { server: string; domain: string | null } | null {
  const candidates: MeshSite[] = [];
  const relay = clientRelaySite(snap, c);
  if (relay) candidates.push(relay);
  candidates.push(...meshSites(snap));
  for (const s of candidates) {
    if (s.dnsServer && (c.allowedSiteIds === null || c.allowedSiteIds.includes(s.id))) {
      return { server: s.dnsServer, domain: s.dnsDomain };
    }
  }
  return null;
}

export function generateClientConf(snap: Snapshot, clientId: string): string {
  const c = snap.clients.find((x) => x.id === clientId);
  if (!c) throw new Error(`unknown client "${clientId}"`);

  const lines: string[] = [
    HEADER,
    `# client: ${c.slug}`,
    "",
    "[Interface]",
    `Address = ${c.tunnelIp}/32`,
    `PrivateKey = ${CLIENT_PRIVATE_KEY_PLACEHOLDER}`,
    `MTU = ${snap.settings.mtu}`,
  ];
  const dns = clientDns(snap, c);
  if (dns) lines.push(`DNS = ${dns.server}${dns.domain ? `, ${dns.domain}` : ""}`);

  for (const entry of clientEntrySites(snap, c)) {
    const carried = clientCarriedByEntry(snap, c, entry).sort((a, b) =>
      compareIp(a.gateway.tunnelIp, b.gateway.tunnelIp),
    );
    const ips: string[] = [];
    for (const s of carried) ips.push(`${s.gateway.tunnelIp}/32`, ...sharedCidrs(s));
    const ep = endpointOf(snap, entry);
    if (ep === null) throw new Error(`entry site "${entry.slug}" has no endpoint`);
    lines.push(
      "",
      "[Peer]",
      `# site: ${entry.slug}`,
      `PublicKey = ${entry.gateway.publicKey}`,
      `Endpoint = ${ep}`,
      `AllowedIPs = ${ips.join(", ")}`,
      `PersistentKeepalive = ${snap.settings.keepalive}`,
    );
  }

  return lines.join("\n") + "\n";
}
