package main

import "testing"

const sampleConf = `# Generated by OPNmesh — do not edit; changes are overwritten on reconcile.
# node: site-a

[Interface]
Address = 10.99.0.1/24
ListenPort = 51820
MTU = 1420
PostUp = wg set %i private-key /etc/opnmesh/keys/wg0.key

[Peer]
# site-b
PublicKey = bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb=
Endpoint = 198.51.100.20:51820
AllowedIPs = 10.99.0.2/32, 10.20.0.0/16
`

func TestListenPortOf(t *testing.T) {
	if p := listenPortOf(sampleConf); p != 51820 {
		t.Fatalf("got %d", p)
	}
	if p := listenPortOf("[Interface]\nAddress = 10.0.0.1/24\n"); p != 0 {
		t.Fatalf("expected 0, got %d", p)
	}
}

func TestPrivateKeyPathOf(t *testing.T) {
	if p := privateKeyPathOf(sampleConf); p != "/etc/opnmesh/keys/wg0.key" {
		t.Fatalf("got %q", p)
	}
}

func TestInterfaceSectionIgnoresPeersAndComments(t *testing.T) {
	// Peer-only change: interface sections must compare equal.
	other := sampleConf + "\n[Peer]\n# client: laptop\nPublicKey = ddddddddddddddddddddddddddddddddddddddddddd=\nAllowedIPs = 10.99.1.10/32\n"
	if interfaceSection(sampleConf) != interfaceSection(other) {
		t.Fatal("peer additions must not change the interface section")
	}
	// Port change: must differ.
	changed := "[Interface]\nAddress = 10.99.0.1/24\nListenPort = 443\nMTU = 1420\n"
	if interfaceSection(sampleConf) == interfaceSection(changed) {
		t.Fatal("port change must change the interface section")
	}
}

func TestHashFilesIsOrderIndependentAndContentSensitive(t *testing.T) {
	a := hashFiles(map[string]string{"x": "1", "y": "2"})
	b := hashFiles(map[string]string{"y": "2", "x": "1"})
	if a != b {
		t.Fatal("hash must not depend on map order")
	}
	c := hashFiles(map[string]string{"x": "1", "y": "3"})
	if a == c {
		t.Fatal("hash must change with content")
	}
}

func TestUdpPortFree(t *testing.T) {
	if !udpPortFree(0) {
		t.Fatal("binding an ephemeral port must succeed")
	}
}
