/**
 * nftables ruleset generation, one per gateway.
 *
 * Everything lives in a dedicated `table inet opnmesh` so reloads are atomic
 * (declare + delete + redefine) and operator-managed tables are never touched.
 * The forward chain has `policy accept` — cross-site traffic is allowed by
 * default and OPNmesh adds targeted drops (client isolation, management ACLs).
 *
 * Never generated here, enforced by validator and test: masquerade / SNAT.
 * Source addresses must survive the mesh end to end.
 */
import type { ResolvedConfig, ResolvedSite } from "../schema.js";
import { connectivityMatrix } from "../topology.js";

const WG_IF = "wg0";

function counterName(fromId: string, toId: string): string {
  const clean = (s: string) => s.replace(/-/g, "_");
  return `cnt_${clean(fromId)}_to_${clean(toId)}`;
}

/**
 * Ordered LAN-pairs whose traffic can traverse this gateway: its own site to
 * every reachable remote site (both directions), plus — when it is a transit
 * hub — the pairs it relays for. Drives the tier-2 traffic matrix.
 */
export function counterPairs(cfg: ResolvedConfig, g: ResolvedSite): Array<[ResolvedSite, ResolvedSite]> {
  const pairs: Array<[ResolvedSite, ResolvedSite]> = [];
  const byId = new Map(cfg.sites.map((s) => [s.id, s]));
  for (const e of connectivityMatrix(cfg)) {
    if (e.status.kind === "unreachable") continue;
    const involved = e.a === g.id || e.b === g.id;
    const relays = e.status.kind === "transit" && e.status.via === g.id;
    if (!involved && !relays) continue;
    const a = byId.get(e.a)!;
    const b = byId.get(e.b)!;
    pairs.push([a, b], [b, a]);
  }
  return pairs;
}

export function generateNftables(cfg: ResolvedConfig, siteId: string): string {
  const g = cfg.sites.find((s) => s.id === siteId);
  if (!g) throw new Error(`unknown site "${siteId}"`);
  const mgmt = cfg.policy?.management ?? null;
  const hasMgmt =
    mgmt !== null && (mgmt.adminSources.length > 0 || mgmt.managementDestinations.length > 0);

  const lines: string[] = [
    "#!/usr/sbin/nft -f",
    "# Generated by OPNmesh — do not edit; changes are overwritten on reconcile.",
    `# node: ${g.id}`,
    "",
    // Declare-then-delete makes the reload atomic and idempotent whether or
    // not the table already exists.
    "table inet opnmesh {}",
    "delete table inet opnmesh",
    "",
    "table inet opnmesh {",
  ];

  lines.push(
    "  set clients {",
    "    type ipv4_addr",
    "    flags interval",
    `    elements = { ${cfg.network.clientSubnet} }`,
    "  }",
  );

  if (hasMgmt && mgmt.adminSources.length > 0) {
    lines.push(
      "",
      "  set admin_sources {",
      "    type ipv4_addr",
      "    flags interval",
      `    elements = { ${mgmt.adminSources.join(", ")} }`,
      "  }",
    );
  }
  if (hasMgmt && mgmt.managementDestinations.length > 0) {
    lines.push(
      "",
      "  set mgmt_destinations {",
      "    type ipv4_addr",
      "    flags interval",
      `    elements = { ${mgmt.managementDestinations.join(", ")} }`,
      "  }",
    );
  }

  const pairs = counterPairs(cfg, g);
  if (pairs.length > 0) lines.push("");
  for (const [from, to] of pairs) {
    lines.push(`  counter ${counterName(from.id, to.id)} {}`);
  }

  lines.push("", "  chain forward {", "    type filter hook forward priority filter; policy accept;");

  lines.push(
    "",
    "    # MTU: clamp TCP MSS to the tunnel path MTU in both directions.",
    `    oifname "${WG_IF}" tcp flags syn tcp option maxseg size set rt mtu`,
    `    iifname "${WG_IF}" tcp flags syn tcp option maxseg size set rt mtu`,
  );

  lines.push(
    "",
    "    # Client isolation: clients reach in; nothing may open a connection to a client.",
    `    oifname "${WG_IF}" ip daddr @clients ct state established,related accept`,
    `    oifname "${WG_IF}" ip daddr @clients ct state new drop`,
  );

  if (hasMgmt && mgmt.managementDestinations.length > 0) {
    lines.push("", "    # Management ACLs: admin sources only, and management never initiates across the mesh.");
    if (mgmt.adminSources.length > 0) {
      lines.push(
        "    ip saddr @admin_sources ip daddr @mgmt_destinations ct state new accept",
      );
    }
    lines.push(
      `    oifname "${WG_IF}" ip saddr @mgmt_destinations ct state new drop`,
      "    ip daddr @mgmt_destinations ct state new drop",
    );
  }

  if (pairs.length > 0) {
    lines.push("", "    # Tier-2 traffic matrix: per site-pair byte/packet counters.");
    for (const [from, to] of pairs) {
      lines.push(
        `    ip saddr ${from.lan} ip daddr ${to.lan} counter name "${counterName(from.id, to.id)}"`,
      );
    }
  }

  lines.push("  }", "}");
  return lines.join("\n") + "\n";
}
