/** sysctl fragment for gateways: forwarding on, nothing else touched. */
import type { ResolvedConfig } from "../schema.js";

export function generateSysctl(cfg: ResolvedConfig, siteId: string): string {
  const g = cfg.sites.find((s) => s.id === siteId);
  if (!g) throw new Error(`unknown site "${siteId}"`);
  return [
    "# Generated by OPNmesh — do not edit; changes are overwritten on reconcile.",
    `# node: ${g.id}`,
    "net.ipv4.ip_forward = 1",
    "",
  ].join("\n");
}
