/** sysctl fragment for gateways: forwarding on, nothing else touched. */
import type { ResolvedConfig } from "../schema.js";

export function generateSysctl(cfg: ResolvedConfig, siteId: string): string {
  const g = cfg.sites.find((s) => s.id === siteId);
  if (!g) throw new Error(`unknown site "${siteId}"`);
  const lines = [
    "# Generated by OPNmesh — do not edit; changes are overwritten on reconcile.",
    `# node: ${g.id}`,
    "net.ipv4.ip_forward = 1",
  ];
  if (g.gateway.flows) {
    // Tier-3 flow records source byte counts from conntrack accounting.
    lines.push("net.netfilter.nf_conntrack_acct = 1");
  }
  return lines.join("\n") + "\n";
}
