/**
 * wg0.conf generation for gateways and named clients.
 *
 * Invariants enforced here (and re-checked independently in lib/validators):
 *  - AllowedIPs per peer is exactly: that peer's tunnel /32, its LAN, the
 *    subnets it is the designated transit for, and the client /32s it carries.
 *    Never 0.0.0.0/0, never anything unexplained.
 *  - No private key ever appears. Gateways load theirs from a path on the node
 *    via `wg set`; client configs carry a placeholder filled in on the device.
 *  - No display name appears — names are cosmetic; site/client *ids* label peers.
 *  - No port literal is hardcoded: every Endpoint and ListenPort comes from
 *    the resolved config.
 *  - Output is fully deterministic (peers sorted by tunnel IP, no timestamps)
 *    so unchanged input produces byte-identical output and clean diffs.
 */
import type { ResolvedConfig, ResolvedSite, ResolvedClient } from "../schema.js";
import { compareIp, parseCidr } from "../ip.js";
import {
  arePeered,
  transitDestinationsVia,
  clientRouteFrom,
  clientPathTo,
} from "../topology.js";

export const CLIENT_PRIVATE_KEY_PLACEHOLDER = "{{CLIENT_PRIVATE_KEY}}";

const HEADER = "# Generated by OPNmesh — do not edit; changes are overwritten on reconcile.";

function endpointOf(site: ResolvedSite): string | null {
  if (site.gateway.endpoint === null) return null;
  return `${site.gateway.endpoint}:${site.gateway.listenPort}`;
}

/**
 * AllowedIPs another gateway lists for peer `p`, seen from gateway `g`.
 * Multi-VLAN sites contribute every advertised subnet; guest segments are
 * absent from `advertised` and therefore never routable across the mesh.
 */
export function gatewayPeerAllowedIps(cfg: ResolvedConfig, g: ResolvedSite, p: ResolvedSite): string[] {
  const ips: string[] = [`${p.gateway.tunnelIp}/32`, ...p.advertised];
  const transits = transitDestinationsVia(cfg, g.id, p.id)
    .map((id) => cfg.sites.find((s) => s.id === id)!)
    .sort((a, b) => compareIp(a.gateway.tunnelIp, b.gateway.tunnelIp));
  for (const t of transits) {
    ips.push(`${t.gateway.tunnelIp}/32`, ...t.advertised);
  }
  const carried = cfg.clients
    .filter((c) => clientRouteFrom(cfg, g.id, c) === p.id)
    .sort((a, b) => compareIp(a.tunnelIp, b.tunnelIp));
  for (const c of carried) ips.push(`${c.tunnelIp}/32`);
  return ips;
}

export function generateGatewayConfig(cfg: ResolvedConfig, siteId: string): string {
  const g = cfg.sites.find((s) => s.id === siteId);
  if (!g) throw new Error(`unknown site "${siteId}"`);
  const subnetPrefix = parseCidr(cfg.network.gatewaySubnet).prefix;

  const lines: string[] = [
    HEADER,
    `# node: ${g.id}`,
    "",
    "[Interface]",
    `Address = ${g.gateway.tunnelIp}/${subnetPrefix}`,
    `ListenPort = ${g.gateway.listenPort}`,
    `MTU = ${g.gateway.mtu}`,
    // The private key is set from a root-only file on the node itself; it is
    // never present in this file, the config repo, the database, or a log.
    `PostUp = wg set %i private-key ${g.gateway.privateKeyPath}`,
  ];

  const peers = cfg.sites
    .filter((p) => p.id !== g.id && arePeered(cfg, g.id, p.id))
    .sort((a, b) => compareIp(a.gateway.tunnelIp, b.gateway.tunnelIp));

  for (const p of peers) {
    lines.push("", "[Peer]", `# ${p.id}`, `PublicKey = ${p.gateway.publicKey}`);
    const ep = endpointOf(p);
    if (ep !== null) lines.push(`Endpoint = ${ep}`);
    lines.push(`AllowedIPs = ${gatewayPeerAllowedIps(cfg, g, p).join(", ")}`);
    // A NAT-bound gateway must dial out and keep the mapping alive; a
    // reachable gateway lets peers come to it.
    if (g.gateway.endpoint === null) {
      lines.push(`PersistentKeepalive = ${cfg.network.keepalive}`);
    }
  }

  const clientPeers = cfg.clients
    .filter((c) => c.entryPoints.includes(g.id))
    .sort((a, b) => compareIp(a.tunnelIp, b.tunnelIp));

  for (const c of clientPeers) {
    lines.push(
      "",
      "[Peer]",
      `# client: ${c.id}`,
      `PublicKey = ${c.publicKey}`,
      // Roaming client: no Endpoint — learned from its handshake. Exactly its
      // /32: a client may never carry another prefix.
      `AllowedIPs = ${c.tunnelIp}/32`,
    );
  }

  return lines.join("\n") + "\n";
}

export function generateClientConfig(cfg: ResolvedConfig, clientId: string): string {
  const c = cfg.clients.find((x) => x.id === clientId);
  if (!c) throw new Error(`unknown client "${clientId}"`);

  const lines: string[] = [
    HEADER,
    `# client: ${c.id}`,
    "",
    "[Interface]",
    `Address = ${c.tunnelIp}/32`,
    // Filled in on the device or in the browser; the control node never sees it.
    `PrivateKey = ${CLIENT_PRIVATE_KEY_PLACEHOLDER}`,
    `MTU = ${c.mtu}`,
  ];

  // Entry points in admin-set preference order (not IP order): the order is
  // meaningful for failover documentation even though WireGuard itself treats
  // peers equally.
  for (const entryId of c.entryPoints) {
    const entry = cfg.sites.find((s) => s.id === entryId)!;
    const ips: string[] = [`${entry.gateway.tunnelIp}/32`, ...entry.advertised];
    const carried = cfg.sites
      .filter((d) => d.id !== entryId && clientPathTo(cfg, c, d.id) === entryId)
      .sort((a, b) => compareIp(a.gateway.tunnelIp, b.gateway.tunnelIp));
    for (const d of carried) ips.push(`${d.gateway.tunnelIp}/32`, ...d.advertised);

    lines.push("", "[Peer]", `# entry: ${entry.id}`, `PublicKey = ${entry.gateway.publicKey}`);
    const ep = endpointOf(entry);
    if (ep === null) {
      throw new Error(
        `client "${c.id}" entry point "${entry.id}" has no endpoint — resolution should have rejected this`,
      );
    }
    lines.push(
      `Endpoint = ${ep}`,
      `AllowedIPs = ${ips.join(", ")}`,
      // Clients are assumed to be behind NAT; keep the mapping alive.
      `PersistentKeepalive = ${cfg.network.keepalive}`,
    );
  }

  return lines.join("\n") + "\n";
}
